### ISSUE TITLE
Reap pods using more than memory limit

### ISSUE THREAD

**Issue by morganchristiansson** [ptagr/pod-reaper#2]
Hello,
I have a problem with long running pods leaking memory.
Can memory usage metric be made an additional metric for reaping pods? And not just age metric.

**Comment by blixhavn** [comment]
Couldn't you just use resource limits here?

**Comment by morganchristiansson** [comment]
Resource limits use kill -9 / hard kill and I was interested in graceful pod shutdown.

I ended up writing a cronjob to delete pods using above limit instead, and later the memory leak issue was resolved.

This is 3 year old issue and not relevant for me anymore.
